# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='man',
            options={},
        ),
    ]
