# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_auto_20170312_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='followers.Man'),
        ),
    ]
